from __future__ import annotations
from app.models.catalog import CENTRAL_AND_SCHOOL_TABLES
from app.models.tables import (
    Addon,
    AddonSubscription,
    Announcement,
    Attendance,
    AuditLog,
    Exam,
    Expense,
    Fee,
    Leave,
    Notification,
    Package,
    School,
    SchoolClass,
    Student,
    Subject,
    Subscription,
    SubscriptionBill,
    SystemSetting,
    User,
)

__all__ = [
    "CENTRAL_AND_SCHOOL_TABLES",
    "Addon",
    "AddonSubscription",
    "Announcement",
    "Attendance",
    "AuditLog",
    "Exam",
    "Expense",
    "Fee",
    "Leave",
    "Notification",
    "Package",
    "School",
    "SchoolClass",
    "Student",
    "Subject",
    "Subscription",
    "SubscriptionBill",
    "SystemSetting",
    "User",
]
