"""Table names created by the Laravel central and per-school migrations.

SQLAlchemy models below map the columns the migrated API reads and writes.
Later version migrations add columns; unmapped columns stay in MySQL and are
left untouched. This registry does not emit DDL against MySQL.
"""
from __future__ import annotations

CENTRAL_AND_SCHOOL_TABLES = (
    "users",
    "password_resets",
    "failed_jobs",
    "personal_access_tokens",
    "permissions",
    "roles",
    "model_has_permissions",
    "model_has_roles",
    "role_has_permissions",
    "schools",
    "categories",
    "sections",
    "mediums",
    "session_years",
    "semesters",
    "languages",
    "sliders",
    "subjects",
    "streams",
    "shifts",
    "classes",
    "elective_subject_groups",
    "class_subjects",
    "staffs",
    "class_sections",
    "students",
    "student_subjects",
    "subject_teachers",
    "lessons",
    "lesson_topics",
    "assignments",
    "assignment_submissions",
    "exams",
    "exam_timetables",
    "exam_marks",
    "exam_results",
    "grades",
    "timetables",
    "announcements",
    "academic_calendars",
    "attendances",
    "files",
    "holidays",
    "promote_students",
    "online_exams",
    "online_exam_questions",
    "online_exam_question_options",
    "online_exam_question_choices",
    "student_online_exam_statuses",
    "online_exam_student_answers",
    "form_fields",
    "extra_student_datas",
    "school_settings",
    "system_settings",
    "class_teachers",
    "packages",
    "announcement_classes",
    "features",
    "package_features",
    "fees",
    "installment_fees",
    "fees_types",
    "fees_classes",
    "payment_transactions",
    "fees_paids",
    "compulsory_fees",
    "optional_fees",
    "subscriptions",
    "addons",
    "addon_subscriptions",
    "subscription_bills",
    "expense_categories",
    "expenses",
    "payment_configurations",
    "leaves",
    "staff_support_schools",
    "faqs",
    "subscription_features",
)
